### ISSUE TITLE
Use JsSourceParser as default parser for AstAnalyser class

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/js-x-ray#223] opened 2024-01-30 20:01 UTC
The parser argument in the constructor of AstAnalyser class is currently required:

https://github.com/NodeSecure/js-x-ray/blob/master/src/AstAnalyser.js#L18

For me we should make it optional and assign `new JsSourceParser()` by default.

**Comment by madina0801** [comment] 2024-01-31 02:42
Hi, I would like to work on it! Could you please assign it to me?

**Comment by jean-michelet** [comment] 2024-01-31 10:31
Go for it Madina, I think the issue is quite simple.

**Closed** 2024-02-02 17:49 UTC
Labels: good first issue
